export type AwsServiceCategory =
    | "Analytics"
    | "Application Integration"
    | "Blockchain"
    | "Business Applications"
    | "Cloud Financial Management"
    | "Compute"
    | "Containers"
    | "Customer Enablement"
    | "Database"
    | "Developer Tools"
    | "End User Computing"
    | "Front-End Web and Mobile"
    | "Game Tech"
    | "Internet of Things (IoT)"
    | "Machine Learning"
    | "Management and Governance"
    | "Media Services"
    | "Migration and Transfer"
    | "Networking and Content Delivery"
    | "Quantum Technologies"
    | "Robotics"
    | "Satellite"
    | "Security, Identity, and Compliance"
    | "Storage";
